### ISSUE TITLE
Argos_ls, Argos_kf, and FastGPS all in the same deployment

### ISSUE THREAD

**Issue by jmlondon** [dsjohnson/crawlUtils#2]
I think you asked at one point if this ever happened and I confidently said, no way!, doesn't happen!

Well, I was wrong ... I have a deployment with all three. I think what has happened is that, for some reason unknown, there are a small percentage of Argos locations for which the kf was not properly calculated so only the ls quality is available. 

Since it seems like it's difficult/impossible to add functionality to accommodate both Argos_ls and Argos_kf, I would suggest we add a feature to the function that selects the Argos type with the highest percentage in the data and filters out the other Argos type. Would throw a warning so the user is aware.

**Comment by dsjohnson** [comment]
In theory it's not hard to handle all 3 at once, but crwMLE was designed to have 1 error model and fixPar applied to the whole deployment. With LS and KF/FastGPS there are different fixPar necessary to avoid estimating unnecessary parameters. So, without a re-write of the core likelihood calculation it can't handle the mixture when you keep the parameters to the bare minimum. I might be able to come up with a clever way to have a large super-model that encompasses both, but I'll have to do some serious thinking.

**Comment by jmlondon** [comment]
this seems like a sensible solution, for now. so closing
