### ISSUE TITLE
Playing around with the kde funcs

### ISSUE THREAD

**Issue by jmhatch** [dsjohnson/crawlUtils#7]
Hi,

I'm playing around with the kde capabilities in `crawlUtils`. I have run into some potential issues, so I wanted to flag them here:

1. In `crawlUtils / R / ud_funcs.R` on line 209 I think `attr(out, "grid_id") <- attr(grid, "grid_id")` should be ` attr(gorig, "grid_id") <- attr(grid, "grid_id")`?
2. When I fix the issue listed above in bullet 1 (just a local copy / paste hack job), and then try to call `cu_kde_ud()` I get an error msg `Error in kde_estimate(grid = xy_grid, points = xy_pts, B = solve(B), norm = norm) : 
  could not find function "kde_estimate"`?

I installed `crawlUtils` using `remotes`. I'm using `crawl 2.3.0 (2022-10-06)` and `crawlUtils 0.1.20 (2022-12-05)`.  

A MWE below,

```
## MWE

# libraries
library(sf)
library(dplyr)
library(magrittr)
library(tidyr)
library(crawl)
library(crawlUtils)

# load example data
data(harborSeal)

## re-project
harborSeal %<>% drop_na(any_of(c('longitude', 'latitude'))) %>%
  st_as_sf(coords = c('longitude', 'latitude'), crs = 4326) %>% 
  st_transform(3338) %>%
  arrange(Time) %>% 
  mutate(Argos_loc_class = factor(Argos_loc_class, levels = c('3', '2', '1', '0', 'A', 'B')))

## fit ctcrw movement model
fixPar = c(log(250), log(500), log(1500), rep(NA, 5))
displayPar(mov.model = ~1, err.model = list(x = ~Argos_loc_class - 1), data = harborSeal, fixPar = fixPar)
constr = list(
  lower = c(rep(log(1500), 3), rep(-Inf, 2)),
  upper = rep(Inf, 5)
)
fit1 = crwMLE(
  mov.model = ~1, err.model = list(x = ~Argos_loc_class - 1), 
  data = harborSeal, coord = c('x', 'y'), Time.name = 'Time', 
  fixPar = fixPar, theta = c(rep(log(5000), 3), 8, 0),
  constr = constr, method = "L-BFGS-B",
  control = list(maxit = 2000, trace = 1, REPORT = 1)
)

## kde
pts = fit1$data %>%
  st_as_sf(coords = c('x', 'y'), crs = 3338)
grid = cu_ud_grid(st_bbox(pts))
ex_kde = cu_kde_ud(pts, grid)
# Error 1: Error in cu_kde_ud(pts, grid) : object 'out' not found
# Error 2: Error in kde_estimate(grid = xy_grid, points = xy_pts, B = solve(B), norm = norm) : 
  could not find function "kde_estimate"
```

Thanks!

**Comment by dsjohnson** [comment]
Thanks for the heads-up. v 0.1.21 should fix this problem. Let me know if it's still throwing an error.
--Devin

**Comment by jmhatch** [comment]
Awesome, thanks! Works like a charm. And I really appreciate all the hard work you've put into the `{crawl}`-verse. Great stuff!
